version: '3.7'

services:
  php:
    build:
      context: .
    volumes:
      - ../.:/var/www/html
    networks:
      - my_network

  nginx:
    image: nginx:1.24.0
    ports:
      - "80:80"
    volumes:
      - ./images/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../.:/var/www/html:ro
    networks:
      - my_network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge  